import React, { useState, useMemo, useEffect } from 'react';
import { JournalEntry, JournalSummary } from '../types';
import { generateReportSummary } from '../services/geminiService';
import { ArrowLeftIcon, ShareIcon, MoodIcon, SymptomIcon, FoodIcon, FireIcon, ChatBubbleBottomCenterTextIcon } from './icons';

interface ReportGeneratorScreenProps {
  journalEntries: JournalEntry[];
  onBack: () => void;
}

type Timeframe = '3d' | '7d' | '30d';

interface ReportData {
    aiTitle: string;
    aiSummary: string;
    timeframe: Timeframe;
    dateRange: string;
    avgWellness: number;
    avgRisk: number;
    topSymptoms: [string, number][];
    topMoods: [string, number][];
    potentialTriggers: [string, number][];
}

const WellnessReport: React.FC<{ data: ReportData }> = ({ data }) => {
    const wellnessColor = data.avgWellness < 4 ? 'text-red-400' : data.avgWellness < 7 ? 'text-yellow-400' : 'text-green-400';
    const riskColor = data.avgRisk > 66 ? 'text-red-400' : data.avgRisk > 33 ? 'text-yellow-400' : 'text-green-400';

    return (
        <div id="wellness-report-content" className="bg-slate-800/50 rounded-lg p-4 sm:p-6 border border-slate-700/50">
            <header className="text-center pb-4 border-b border-slate-700/50">
                <h2 className="text-2xl font-bold text-cyan-300">{data.aiTitle}</h2>
                <p className="text-sm text-slate-400">{data.dateRange}</p>
            </header>
            
            <div className="my-6 grid grid-cols-2 gap-4 text-center">
                <div>
                    <p className="text-sm text-slate-400">Avg. Wellness</p>
                    <p className={`text-5xl font-bold ${wellnessColor}`}>{data.avgWellness.toFixed(1)}</p>
                </div>
                <div>
                    <p className="text-sm text-slate-400">Avg. Flare-Up Risk</p>
                    <p className={`text-5xl font-bold ${riskColor}`}>{Math.round(data.avgRisk)}<span className="text-3xl">%</span></p>
                </div>
            </div>

            <div className="bg-slate-900/40 rounded-lg p-4 mb-6">
                <h3 className="text-lg font-semibold text-slate-300 mb-2 flex items-center gap-2">
                    <ChatBubbleBottomCenterTextIcon className="w-6 h-6 text-cyan-400" /> AI Summary
                </h3>
                <p className="text-slate-300 text-sm">{data.aiSummary}</p>
            </div>

            <div className="grid md:grid-cols-2 gap-6 text-sm">
                <div>
                    <h3 className="font-semibold text-slate-300 mb-2 flex items-center gap-2"><SymptomIcon className="w-5 h-5" />Top Symptoms</h3>
                    {data.topSymptoms.length > 0 ? (
                        <ul className="space-y-1">
                            {data.topSymptoms.map(([symptom, count]) => <li key={symptom} className="flex justify-between"><span>{symptom}</span> <span className="font-mono text-slate-400">{count}d</span></li>)}
                        </ul>
                    ) : <p className="text-slate-500 italic">No recurring symptoms.</p>}
                </div>
                <div>
                    <h3 className="font-semibold text-slate-300 mb-2 flex items-center gap-2"><MoodIcon className="w-5 h-5" />Top Moods</h3>
                    {data.topMoods.length > 0 ? (
                        <ul className="space-y-1">
                            {data.topMoods.map(([mood, count]) => <li key={mood} className="flex justify-between"><span>{mood}</span> <span className="font-mono text-slate-400">{count}d</span></li>)}
                        </ul>
                    ) : <p className="text-slate-500 italic">No recurring moods.</p>}
                </div>
                <div className="md:col-span-2">
                    <h3 className="font-semibold text-slate-300 mb-2 flex items-center gap-2"><FoodIcon className="w-5 h-5" />Potential Triggers</h3>
                    {data.potentialTriggers.length > 0 ? (
                        <div className="flex flex-wrap gap-2">
                           {data.potentialTriggers.map(([food]) => <span key={food} className="bg-yellow-500/20 text-yellow-300 px-2 py-1 rounded capitalize font-medium">{food}</span>)}
                        </div>
                    ) : <p className="text-slate-500 italic">No clear food triggers identified in this period.</p>}
                </div>
            </div>
             <footer className="text-center text-xs text-slate-600 pt-6 mt-6 border-t border-slate-700/50">
                Report generated by IBD Nexus. This is not medical advice.
             </footer>
        </div>
    );
};


const ReportGeneratorScreen: React.FC<ReportGeneratorScreenProps> = ({ journalEntries, onBack }) => {
    const [timeframe, setTimeframe] = useState<Timeframe>('7d');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [reportData, setReportData] = useState<ReportData | null>(null);
    
    const countOccurrences = (items: string[]) => {
        const counts = items.reduce((acc, item) => {
            acc[item] = (acc[item] || 0) + 1;
            return acc;
        }, {} as Record<string, number>);
        return Object.entries(counts).sort((a, b) => b[1] - a[1]);
    };

    const handleGenerateReport = async () => {
        setIsLoading(true);
        setError(null);
        setReportData(null);

        const days = parseInt(timeframe.replace('d', ''), 10);
        const cutoffDate = new Date();
        cutoffDate.setDate(cutoffDate.getDate() - days);

        const filteredEntries = journalEntries.filter(entry => new Date(entry.date) >= cutoffDate);
        
        if (filteredEntries.length < 2) {
            setError(`You need at least 2 entries in the last ${days} days to generate a report.`);
            setIsLoading(false);
            return;
        }

        const summaries = filteredEntries.map(e => e.summary);
        const { title, summary } = await generateReportSummary(summaries, days);

        const avgWellness = summaries.reduce((acc, s) => acc + s.mentalWellnessScore, 0) / summaries.length;
        const avgRisk = summaries.reduce((acc, s) => acc + s.flareUpRisk, 0) / summaries.length;
        
        const allSymptoms = summaries.flatMap(s => s.physicalSymptoms);
        const topSymptoms = countOccurrences(allSymptoms).slice(0, 3);
        
        const allMoods = summaries.flatMap(s => s.moods);
        const topMoods = countOccurrences(allMoods).slice(0, 3);

        const foodStats: Record<string, { badDays: number; total: number }> = {};
        summaries.forEach(s => {
            const isBadDay = s.flareUpRisk > 60 || s.crampsSeverity! > 6;
            s.foodEaten.forEach(food => {
                const normalized = food.toLowerCase().trim();
                if (!foodStats[normalized]) foodStats[normalized] = { badDays: 0, total: 0 };
                if (isBadDay) foodStats[normalized].badDays++;
                foodStats[normalized].total++;
            });
        });
        
        const potentialTriggers = Object.entries(foodStats)
            .filter(([, stats]) => stats.total >= 2 && (stats.badDays / stats.total) > 0.6)
            .sort((a, b) => (b[1].badDays / b[1].total) - (a[1].badDays / a[1].total))
            .slice(0, 3);

        const endDate = new Date();
        const startDate = new Date();
        startDate.setDate(endDate.getDate() - days);
        const dateFormatter = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' });
        
        setReportData({
            aiTitle: title,
            aiSummary: summary,
            timeframe,
            dateRange: `${dateFormatter.format(startDate)} - ${dateFormatter.format(endDate)}`,
            avgWellness,
            avgRisk,
            topSymptoms: topSymptoms.map(([name, count]) => [name, count]),
            potentialTriggers: potentialTriggers.map(([name, stats]) => [name, stats.badDays]),
            topMoods: topMoods.map(([name, count]) => [name, count]),
        });

        setIsLoading(false);
    };

    const generateTextSummary = (): { title: string, text: string } => {
        if (!reportData) return { title: '', text: '' };
        
        let summary = `Wellness Report: ${reportData.aiTitle}\n`;
        summary += `Period: ${reportData.dateRange}\n\n`;
        summary += `--- AI SUMMARY ---\n${reportData.aiSummary}\n\n`;
        summary += `--- KEY METRICS ---\n`;
        summary += `• Average Wellness Score: ${reportData.avgWellness.toFixed(1)}/10\n`;
        summary += `• Average Flare-Up Risk: ${Math.round(reportData.avgRisk)}%\n\n`;
        
        summary += `--- TOP SYMPTOMS ---\n`;
        reportData.topSymptoms.forEach(([s, c]) => summary += `• ${s} (${c} days)\n`);
        if (reportData.topSymptoms.length === 0) summary += "No recurring symptoms noted.\n";
        summary += `\n`;
        
        summary += `--- POTENTIAL TRIGGERS ---\n`;
        reportData.potentialTriggers.forEach(([f]) => summary += `• ${f}\n`);
        if (reportData.potentialTriggers.length === 0) summary += "No clear food triggers identified.\n";
        
        summary += "\n---\nGenerated by IBD Nexus. Not medical advice.";
        
        return { title: `Wellness Report - ${reportData.dateRange}`, text: summary };
    };

    const handleShare = async () => {
        if (!navigator.share || !reportData) {
            alert("Sharing is not supported on this browser, or no report is generated.");
            return;
        }
        const { title, text } = generateTextSummary();
        try {
            await navigator.share({ title, text });
        } catch (error) {
            console.error("Error sharing:", error);
        }
    };

    const handleDownload = () => {
        if (!reportData) return;
        const { title, text } = generateTextSummary();
        const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${title.replace(/ /g, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="p-4 sm:p-6 pb-24 text-white overflow-y-auto h-full flex flex-col">
            <header className="mb-6 flex items-center relative flex-shrink-0">
                <button onClick={onBack} className="absolute left-0 top-1/2 -translate-y-1/2 p-2 rounded-full hover:bg-slate-700/50 transition-colors" aria-label="Go back to dashboard">
                    <ArrowLeftIcon className="w-6 h-6 text-slate-300" />
                </button>
                <div className="flex-grow text-center">
                    <h1 className="text-3xl font-bold text-cyan-300">Generate Report</h1>
                    <p className="text-slate-400">Create a wellness summary.</p>
                </div>
            </header>
            
            {!reportData && (
                <div className="flex-grow flex flex-col items-center justify-center text-center">
                    <div className="w-full max-w-sm">
                        <p className="mb-4 text-slate-300">Select a time frame for your report:</p>
                        <div className="grid grid-cols-3 gap-2 bg-slate-800 p-1 rounded-full mb-8">
                            {(['3d', '7d', '30d'] as Timeframe[]).map(tf => (
                                <button key={tf} onClick={() => setTimeframe(tf)} className={`px-4 py-2 text-sm rounded-full transition-colors ${timeframe === tf ? 'bg-cyan-500 font-semibold' : 'hover:bg-slate-700'}`}>
                                    Last {tf.replace('d', '')} days
                                </button>
                            ))}
                        </div>
                        <button onClick={handleGenerateReport} disabled={isLoading} className="w-full py-3 bg-cyan-500 rounded-lg text-lg font-semibold hover:bg-cyan-400 transition-colors disabled:bg-slate-600 disabled:cursor-not-allowed flex items-center justify-center">
                            {isLoading && <svg className="animate-spin -ml-1 mr-3 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>}
                            {isLoading ? 'Generating...' : 'Generate Report'}
                        </button>
                        {error && <p className="mt-4 text-red-400">{error}</p>}
                    </div>
                </div>
            )}

            {reportData && (
                 <div className="w-full max-w-2xl mx-auto">
                    <WellnessReport data={reportData} />
                    <div className="mt-6 space-y-3">
                        <button onClick={handleShare} className="w-full flex items-center justify-center gap-2 py-3 bg-cyan-500 rounded-lg text-lg font-semibold hover:bg-cyan-400 transition-colors">
                            <ShareIcon className="w-6 h-6" />
                            Share Report
                        </button>
                         <button onClick={handleDownload} className="w-full py-2 bg-slate-700/80 rounded-lg text-sm font-semibold hover:bg-slate-700 transition-colors">
                            Download as .txt
                        </button>
                        <button onClick={() => setReportData(null)} className="w-full text-center text-cyan-400 hover:text-cyan-300 text-sm font-medium">
                            Generate New Report
                        </button>
                        <p className="text-center text-xs text-slate-500 pt-2">Tip: Take a screenshot of the report above for a visual copy to share.</p>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ReportGeneratorScreen;